version: "3"

services:
  gateway:
    image: gateway:latest
    container_name: gateway
    hostname: gateway
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./lib:/app/lib
  appserver:
    image: appserver:latest
    container_name: appserver
    hostname: appserver
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./lib:/app/lib      
  dataserver:
    image: dataserver:latest
    container_name: dataserver
    hostname: dataserver
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./lib:/app/lib
    
